[package]
name = "monkey"
version = "1.0.0"
edition = "2024"

[dependencies]
rustyline = "17.0.2"
thiserror = "2.0.11"
strum = { version = "0.27.2", features = ["derive"] }
ariadne = "0.6.0"
clap = { version = "4.5.53", features = ["derive"] }
itertools = "0.14.0"
